### ISSUE TITLE
Client.get example never kept nor broken

### ISSUE THREAD

**Issue by albastev** [croservices/cro#30]
I have had good success with the Cro Router and Server, but Cro::HTTP::Client gives me grief. Any request I have tried running results in a promise that is neither kept nor broken. e.g.

    my $resp = await Cro::HTTP::Client.get('https://www.perl6.org/'); 

I am running Cro::Core:ver('0.7') with Rakudo 2017.08-59-g0bc1c8774 on Debian 9 in an EC2 instance.
I can ping the external site just fine from the command line.

I suppose that there may be something blocking rakudo from accessing the network, but the eternal hanging and no hint as to what is wrong seems to be a bad behavior.

Otherwise, this is a very neat project. Thank you!

**Comment by albastev** [comment]
I have been experimenting with it tonight, and zef installed Net::HTTP. That works for me, so it looks like clients can reach the outside world from Perl 6.

**Comment by Altai-man** [comment]
What is your rakudo version? Do you use latest commit of cro-http?

**Comment by albastev** [comment]
Hello,

I am running Cro::Core:ver('0.7') with Rakudo 2017.08-59-g0bc1c8774 on Debian 9 in an EC2 instance.

**Comment by jnthn** [comment]
The latest Cro release has fixed quite a good number of issues in `Cro::HTTP::Client`, including a number that could cause hangs (the trickiest of which turned out to be a Rakudo bug that I've reported upstream, and put in a workaround into Cro for). I'm fairly confident whichever of the hangs you ran into is now gone, though if you encounter one again please do let us know. Thanks!

**Comment by albastev** [comment]
Ok, I will check it out. Thanks!
