### ISSUE TITLE
how to pass a hash in response

### ISSUE THREAD

**Issue by tbrowder** [croservices/cro#31]
Can a route pass a hash back in a response?  If so, the Cro::HTTP[S]::Server could emulate a CGI server by returning the standard CGI [with TLS extensions] %*ENV hash with known values for testing.

**Comment by jnthn** [comment]
I'm not sure I understand the question, but maybe this will help...

A route maps a `Cro::HTTP::Request` into a `Cro::HTTP::Response`, the latter being created for you, and available by the `response` term. More often, though, the content of the response is set using the `content` function. A hash is a Perl 6 data structure, so would need serializing as part of the HTTP response. Since we have built-in JSON serialization support, doing that for JSON would just be something like `content 'application/json', %hash`.

**Comment by tbrowder** [comment]
Thanks, @jnthn, I’ll keep eperimenting in that direction.
