### ISSUE TITLE
recommend dev on one branch, stable release on another

### ISSUE THREAD

**Issue by tbrowder** [croservices/cro#32]
Due to the entry in your Cro modules for the perl 6 ecosystem (/path/to/master/branch), any travis build gets the latest commit and any test failures (which are happening now).  I have changed one of my modules to track a stable branch (named release) and do dev on the master branch. I have modified my .travis.yml file to test both branches.  I have modified the Perl 6 ecosystem entry to track the release branch (/path/to/release/branch).  That seems to work well for me.

Due to the probable wide use of your CRO services, I think your customers would be better served.

**Comment by jnthn** [comment]
Thanks for the suggestion. Our plan is to switch over to distributing release tarballs by uploading to PAUSE/CPAN, since [zef can install from there for a while now](https://github.com/ugexe/zef#cpan). That way, the git repositories will just be for development. Will leave this ticket open to track us actually doing that step.

**Comment by tbrowder** [comment]
Thanks for the reminder about CPAN!  I will go the same route after I get some answers from ugexe about META6.json entries for CPAN.

**Comment by jnthn** [comment]
Cro 0.7.1 was released today on CPAN, and the META.list references to the Git repositories removed. Hopefully that is a satisfactory resolution for this issue. Thanks for the nudge to make sure the next release was done on CPAN. :-)
