### ISSUE TITLE
PSGI-like middlewares?

### ISSUE THREAD

**Issue by domm** [croservices/cro#55]
I see that you're adding some middlewares to Cro. Are there any plans for something like PSGI/Plack for Cro/Perl6, so that we can avoid the Web-Framework-Trap (c.f. Catalyst, Dancer, Mojo all implementing lot of in theory generic stuff (like Token/Session Handling, ...)) ?

I haven't tried cro (yet), so I'm not sure if cro is more like a web framework (Mojo/Dancer), or more a generic app framework that happens to work good with web, or an abstraction layer / toolkit I can use to build my own web apps (that will also include a significant non-web part (cronjobs, daemons, import/export scripts)

This questions is probably not an 'issue', but afaik there is no mailinglist?

Greetings,
domm

**Comment by jnthn** [comment]
Cro is a set of libraries for building distributed systems. Since web services and applications are one of the most common forms of distributed system, we've focused heavily on that use case first ("first do at least one thing well"). But the heart of Cro - composing components together to form pipelines - is more abstract.

While we use the term "middleware" because it's widely understood, in practice *everything* in Cro is middleware. Requests arrive as a stream of bytes and responses go back as a stream of bytes. Everything between this is a pipeline component, be it a request parser, response serializer, application, or one of the things we'd more traditionally call middleware. Want to replace the HTTP request parser with some super-fast C library? Just write a component that binds it and compose it with the rest. All of these components are just a thin wrapper around the Perl 6 `Supply` type (representing an asynchronous stream). And, while I've talked about the server side here, clients are also pipelines too, it's just that the network is in the middle of the pipeline rather than the start/end.

Atop of that we have some sugar. `Cro::HTTP::Server` builds up a HTTP processing pipeline, to eliminate the boilerplate of doing it by hand. `Cro::HTTP::Router` provides a way of implementing a request to response transform (so, "the application"). And the various `Cro::HTTP::Middleware` roles save a bit of boilerplate for implementing pipeline components that play the middleware role.

Cro has been built - intentionally - so that its components can be re-used as the basis for web frameworks. At the same time, we also provide a bunch of things built atop of them that are aimed at providing a nice way to write HTTP services/applications (which you might choose to call a web framework). If there's demand, those could be split into a couple of distributions, so other web frameworks don't have to depend on the Cro sugar, if they want a smaller footprint.

The scope of Cro is to help with the "distributed system" side of things. With time, we'll provide better support for building ZeroMQ pipelines, as well as for support building services that deal with message queues. Things that help with building such systems in robust ways are also within Cro's mandate (implementations of things like circuit breakers and similar). What is *not* in scope is trying to provide a framework for how people write their business logic, domain models, and so forth. These form the heart of a system, can have value well beyond being exposed to the web/network, are better tested in isolation, and should thus have few dependencies. Effectively, Cro says: write your domain logic how you want, then I'll help you expose it to the world.

I've no idea if others keen to build web frameworks in Perl 6 in the future will decide to re-invent all the wheels, or will adopt the Cro HTTP components and then build the value they want to add atop of that. If Cro's model is to become a de facto standard for middleware, that's fine, but I can only see that happening through adoption by those making web frameworks because they see the value. I don't think declaring "this is the API we'll have for doing Perl 6 web stuff" is wise until there's at least a decent range of consumers of it. While my opinion is that the Cro components are unopinionated enough for wide re-use, others may have different opinions on that. We'll see. :-)

As to mailing list - no, there's not one (yet? :-)). There is an IRC channel (`#cro` on freenode). Also, perhaps some of what I've written here would be good to put into the documentation.

Hope this is at least something of an answer!

**Comment by domm** [comment]
Thanks for the very elaborate answer (and sorry for my lag, I was on holidays..)

> Cro says: write your domain logic how you want, then I'll help you expose it to the world.

This is a very good motto, and aligns with how I do (web) stuff and why I don't really like to bind myself to specific web frameworks anymore.

Anyway, I might make it to the March 1st Brno.pm meeting and would love to discuss this with you even more - but first I will need to actually get my feet wet and try out Cro.
